eregs/regulations-parser

README.md
This should provide a soup-to-nuts working example.
It switches between cfpb repos and 18f repos due to https://github.com/cfpb/regulations-site/issues/698 and https://github.com/cfpb/regulations-parser/pull/265
=> Update README with FEC example and full UI integration

README.md, notice_order.py, regparser/builder.py
Nothing amazing, but this adds a little script that pulls makes it easy to see the order notices will be applied in. Future work includes using checkpoints and writing a common cli framework so that this could be ran with something like `regulations notice_order 12 1026`.
Output examples (skipping warnings):
```bash
(parser)vagrant@debian8:~/regulations-parser$ python notice_order.py 12 1026
2011-12-30
2012-11-23
2012-28341
2013-01-01
2012-27993
2012-27997
2013-03-28
2013-07066
2013-05-03
2013-10429
2013-06-01
2013-00734
2013-01503_20130601
2013-12125
2013-11-21
2014-01-01
2013-01503_20140101
2013-22752_20140101
2013-28195
2013-29844
2013-31225
2014-01-10
2013-00736
2013-00740
2013-01241
2013-01503_20140110
2013-13173
2013-16962
2013-22752_20140110
2013-24521
2014-01-18
2013-01809 …
```
=> Add small program to print out ordered notices

build_from.py, regparser/tree/struct.py, tests/tree_struct_tests.py
This improves memory usage (allowing reg Z to compile on machines with < 1G memory) through a few optimizations.
1. FrozenNodes now have a proper digest hash, which is calculated at their creation time. Equality checks look only at the fields and the hashes, reducing the need to generate a gigantic `repr` string.
1. FrozenNode creation should only occur once. Because they are immutable, we don't need duplicate versions of the same FrozenNode. This means that the majority of the tree is shared between versions which cuts memory usage by about half (for Z)
1. The build_from script includes a few more `del` statements, to indicate memory can be reclaimed.
I also synchronized the build_from script with CFPB's re-order. That'll make merging upstream much easier.
=> Significantly tighten memory usage in build_from

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
The FDSYS XML might include the CFR part in a few different places. For the FEC regs, it was in a different place than the CFPB regs.
Also some cleanup due to flake8 warnings.
=> Account for more FDSYS locations of the CFR part

README.md, build_from.py, regparser/builder.py, regparser/grammar/tokens.py, regparser/notice/changes.py, regparser/notice/compiler.py, tests/notice_changes_tests.py, watch_node.py
README describes what this does, but the hope is that it'd make debugging a little bit easier. Right now, it's possible to manually grep through trees and notices, but it's awfully cumbersome.
This has a lot of duplication with `build_from.py` and doesn't make use of checkpoints, but I think it's still useful in its current form.
Looks like:
```
$ python watch_node.py 1005-16-c fr-notices/articles/xml/201/131/725.xml 12
WARNING:root:Bad format for whole appendix
> 2011-31725
Added: (c) Notice requirement. To meet the requirements of paragraph (b) of this section, an automated teller machine operator must comply with the following:
> 2013-06861
Modified: (c) Notice requirement. An automated teller machine operator must provide the notice required by paragraph (b) of this section either by …
```
=> A "Watch Node" script

regparser/notice/compiler.py, tests/notice_compiler_tests.py
The problem we ran into was that a notice would contain changes to both reg 2 and reg 200. The filter was not properly filtering out the 200 when looking at changes for 2.
=> Bug fix around notices containing multiple regs

README.md, build_from.py, regparser/builder.py
Certain regulations haven't changed since before federalregister.gov was keeping electronic copies of notices. In these situations, we'd like to manually specify what version number should be associated with the provided version of the regulation.
I thought the code assumed that the regulation would have a notice associated with it, but I didn't run into any problems with this change. I manually traced through the version generating code as well, and didn't see a problem.
No tests as the changes are occurring in the runner script, which doesn't have a good test harness. The changes are also minor.
=> Allow regs which have no history

regparser/builder.py, regparser/notice/fake.py, regparser/tree/xml_parser/reg_text.py, tests/builder_tests.py, tests/notice_fake_tests.py
This resolves #32 by inserting a fake notice into the system when parsing a regulation which has had no changes since the federal register began digitizing final rules.
It also removes duplicate string-to-xml conversions and removes `Builder.reg_tree` in favor of a direct call to the underlying library. Unlike #34, this has been tested from parsing to display (along with changes to -core and -site)
=> Generate a fake notice when explicitly providing the document number

regparser/grammar/terms.py, regparser/layer/formatting.py, regparser/tree/xml_parser/appendices.py, settings.py, tests/grammar_terms_tests.py, tests/layer_formatting_tests.py, tests/layer_terms_tests.py, tests/tree_xml_parser_appendices_tests.py
These correspond to @willbarton's
* https://github.com/cfpb/regulations-parser/pull/276 Allowing appendices to display `FP-DASH` differently
* https://github.com/cfpb/regulations-parser/pull/279 Allowing terms in unmarked paragraphs
* https://github.com/cfpb/regulations-parser/pull/280 Adds a configuration for ignoring headers in certain regulations
These have already been reviewed once, so no need for deep review.
=> Pull in some code from CFPB

regparser/tree/depth/markers.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/tree_utils.py, tests/tree_utils_tests.py, tests/tree_xml_parser_reg_text_tests.py
Previously, paragraphs like:
> Something something (a) subparagraph (b) another subparagraph
Were getting cut down to just the two subparagraphs. This expands the functionality to account for that extra starting text. It also adds a special marker type, `MARKERLESS`, which will be used significantly in a later update.
Finally, it adds a helper method to `NodeStack` to unwind the stack in one fell swoop.
=> Enhanced "split text"

regparser/tree/depth/derive.py, regparser/tree/depth/rules.py
We will need this performance boost when handling `MARKERLESS` paragraphs. No new tests as we aren't changing any interfaces.
Improvements come in
1. limiting the domain of variables
2. adding more constraints on pairs of variables (rather than longer sequences)
3. reducing the number of constraints by combining constraining functions
Here's a rather gnarly set of markers:
```python
['STARS', 'B', 'C', 'STARS', '1', '2', 'STARS', '1', '2', 'STARS', 'a', 'b', 'STARS', 'F', 'a', 'STARS', 'c', 'd', 'STARS']
```
In `master`, `derive_depths` takes ~18s, down to ~5s with this branch
=> Refactor depth rules to run a bit faster

regparser/tree/depth/derive.py, regparser/tree/depth/markers.py, regparser/tree/depth/rules.py, tests/tree_depth_derive_tests.py
Extends #49 (see [diff](https://github.com/cmc333333/regulations-parser/compare/derive-depth-updates...cmc333333:markerless)) by extending the depth-parser to understand paragraphs without a marker.
There aren't many additional rules, as the rules around such paragraphs are lax:
1. Multiple MARKERLESS paragraphs in sequence must be at the same depth
2. Markers cannot be used to "skip" a paragraph depth level (see code comment for example)
Also included:
* Code to reduce computation over MARKERLESS paragraphs (we can compress multiple due to rule 1 above)
* Refactoring some of the depth parsing tests
=> Allow MARKERLESS paragraphs in the depth-parsing code

regparser/tree/depth/derive.py, regparser/tree/depth/heuristics.py, regparser/tree/depth/markers.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_depth_derive_tests.py, tests/tree_depth_heuristics_tests.py, tests/tree_xml_parser_paragraph_processor_tests.py, tests/tree_xml_parser_reg_text_tests.py
This builds on #51 ([diff](https://github.com/cmc333333/regulations-parser/compare/markerless...cmc333333:markerless-regtext)) to use the updated depth processing for regtext. Effectively, this allows regtext to contain paragraphs without markers.
It does this by
1. Creating a `ParagraphProcessor` class, similar to the `AppendixProcessor`, but with more plugability regarding xml node types. This processor can handle paragraphs without markers
2. Removing the existing regtext parsing in favor of a subclass of `ParagraphProcessor`
3. Adding some additional heuristics around the relationship between paragraph types and depths
~~This needs some additional tests and perhaps a bit of cleanup before it can be merged~~
=> Refactor regtext processor to be more generic

requirements_test.txt, tests/tree_xml_parser_reg_text_tests.py, tests/xml_builder.py
This is a tad more terse, but more importantly: significantly less error prone.
=> Use a DSL when defining XML examples

README.md, regparser/grammar/amdpar.py, regparser/grammar/atomic.py, regparser/grammar/terms.py, regparser/grammar/unified.py, regparser/layer/terms.py, regparser/notice/build.py, regparser/tree/depth/markers.py, settings.py, tests/grammar_amdpar_tests.py, tests/grammar_atomic_tests.py, tests/grammar_interpretation_headers_tests.py, tests/grammar_terms_tests.py, tests/grammar_unified_tests.py, tests/layer_formatting_tests.py, tests/layer_terms_tests.py, tests/notice_build_tests.py, tests/tree_xml_parser_reg_text_tests.py
* https://github.com/cfpb/regulations-parser/pull/282 Allows another citation format for comments
* https://github.com/cfpb/regulations-parser/pull/283 Adds a test for that
* https://github.com/cfpb/regulations-parser/pull/284 Adds an explicit label format in amdpars, along with tweaks to definition grammars
* https://github.com/cfpb/regulations-parser/pull/286 Removes "the act" as an exception in definitions
Pulling in these 4 PRs as they 1) build on each other and 2) affect definitions, which I'm about to change a bit.
=> Pull in CFPB #282, #283, #284, #286

regparser/tree/depth/heuristics.py, regparser/tree/xml_parser/paragraph_processor.py, tests/tree_depth_heuristics_tests.py
Prefer
```
MARKERLESS
a
MARKERLESS
```
over
```
MARKERLESS
a
MARKERLESS
```
=> Add a heuristic to prefer shallow solutions

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
Builds on #54 ([diff](https://github.com/cmc333333/regulations-parser/compare/cmc333333:xml-dsl...cmc333333:fp-markerless)) and resolves one of the issues in #56
=> Allow markerless paragraphs to use the FP tag

regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/layer_formatting_tests.py, tests/tree_xml_parser_reg_text_tests.py, tests/xml_builder.py
Builds on #54 ([diff](https://github.com/cmc333333/regulations-parser/compare/cmc333333:xml-dsl...cmc333333:regtext-table)).
We've been able to process tables as defined in the CFR XML, but only in the appendix. This extends the now-pluggable paragraph parser to account for the tables in regulation text as well.
=> Allow regtext to contain tables

regparser/tree/reg_text.py, regparser/tree/xml_parser/reg_text.py, tests/tree_reg_text_tests.py
Essentially by pretending they're subparts with “letters” we make up from their titles. I don't think we can do much better than this without also changing regulations-site, which is the next stage.
=> Make SUBJGRPs appear in TOC in just-about acceptable fashion

regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
Handles `EXTRACT`, `NOTES`, `NOTE`, `CODE` tags in regtext as we do in appendices. This creates a fenced node, which is converted into formatted text via a layer.
This works but does not look good in `regulations-site`
=> Account for EXTRACT, NOTES, etc. tags in regtext

regparser/layer/def_finders.py, regparser/layer/scope_finder.py, regparser/layer/terms.py, tests/layer_def_finders_tests.py, tests/layer_scope_finder_tests.py, tests/layer_terms_tests.py
Highlights:
* The various matchers for finding definitions have been split out into individual classes. This should be easier to maintain and extend in the future
* Similarly, the logic around determining scope for a definition has been moved to a separate class
* The `Ref` class no longer needs a pair for position (it calculates the end point by adding the term's length). It also automatically lower-cases the term (rather than relying on its caller)
* Split up tests a bit
* Flake8 all the things
* Fixed bug in `INCLUDE_DEFINITIONS_IN` code (referencing a variable which did not exist)
This should not change any functionality
=> Refactor terms layer

regparser/grammar/terms.py, regparser/layer/def_finders.py, regparser/layer/terms.py, regparser/tree/struct.py, tests/layer_def_finders_tests.py
... but only when several conditions also apply.
Builds off #63 ([diff](https://github.com/cmc333333/regulations-parser/compare/cmc333333:refactor-terms...cmc333333:term-improvements))
This also adds a `depth` method to nodes as it is probably more applicable than just the definitions layer.
=> Use what would be keyterms in place of definition

regparser/tree/depth/derive.py, regparser/tree/depth/markers.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_depth_derive_tests.py
This adds a set of constraints on depth parsing to account for a particularly slow resolution to a set of markers @willbarton found:
```python
markers = [u'a', u'* * *', u'2', u'* * *', u'iii', u'STARS', u'b', u'* * *', u'1', u'* * *', u'ii', u'A', u'B', u'C', u'D', u'STARS', u'vi', u'2', u'* * *', u'ii', u'A', u'B', u'C', u'D', u'STARS', u'vi', u'STARS', u'6', u'* * *', u'ii', u'STARS', u'd', u'* * *', u'1', u'* * *', u'ii', u'* * *', u'C']
```
My laptop took over 20 seconds to process only the first 25 (of 38) markers. With these new constraints, that's down to less than half a second for the whole list.
New constraints/updates:
* Assume that `ii` is the roman number 2 (rather than the 35th letter of the lowercase alphabet)
* Limit _regtext_ such that the same marker type can only …
=> Speed up depth parsing

regparser/tree/xml_parser/reg_text.py, tests/node_accessor.py, tests/tree_xml_parser_reg_text_tests.py
* Adds a nicer interface for validating node trees
* Reworks collapsed markers remove some false positives
To understand the second, imagine a paragraph such as
> (a) Examples. (1) aaa, (2) bbb, (3) ccc. Then some closing text
> (b) Paragraph b
The existing logic would split the first paragraph into `(a)` and `(a)(1)`, which made no sense. Even splitting into `(a)`, `(a)(1)`, `(a)(2)`, and `(a)(3)` wouldn't work well as there's text at the tail that's not applicable to `(3)`.
This constrains the logic around collapsed markers to take into account the following paragraph.
> (a) Examples. (1) Some text
> (i) Paragraph i
will continue to be broken into three paragraphs, as will
> (a) Examples. (1) Some text
> (2) More text.
As the `STARS` tag is a place holder,
> (a) Examples. (1) Some text …
=> Tighten rules around collapsed markers

regparser/layer/terms.py, regparser/tree/priority_stack.py, tests/layer_terms_tests.py
This is more-or-less a sanity check. If a definition is too long, it most likely means something went wrong when finding it.
Also splits a really long test into its components.
=> Add a cap to the length of definitions

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
Existing code assumes that `SUBJGRP`s were within `SUBPART`s. This patch allows `SUBJGRP`s to be at the top level (as they are in ATF's 646)
=> Allow subjgrps to be at the top level

regparser/notice/build.py, regparser/notice/preprocessors.py, regparser/notice/util.py, tests/notice_build_tests.py, tests/notice_preprocessors_tests.py
The XML for notices around ATF regs include a relatively common mistake -- the text describing who approved a change is supposed to use the `APPRO` tag but often uses `FP`.
This extends the existing notice pre-processing scripts to account for this. Along the way,
* Split preprocessors into separate classes (a pattern in basically all of my recent pull requests)
* Use the XML DSL in the tests
* Make some of the logic within these scripts easier to follow
Ultimately, this has led to more functionality with fewer lines of code
=> 555 fix: "approved by"

regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
* Combine markerless and marker-full paragraph processing (`get_markers_and_text`) had been updated previously to account for markerless introductions
* Updated to strip whitespace from the tagged text (matching the Markerless processor)
* Account for corner cases where the root node didn't have `tagged_text`
* Test
Resolves 18F/atf-eregs#32
=> Allow collapsed markers in MARKERLESS paragraphs

regparser/notice/compiler.py, regparser/tree/struct.py, tests/notice_compiler_tests.py, tests/tree_struct_tests.py
Previously, the compiling code wouldn't find the parent of a section (i.e. a `SUBPART`/ `EMPTYPART`). This is somewhat dangerous as it's possible some amendment relied on this buggy behavior.
Works with 27 CFR 479, 646 and solves a problem with 555.
Also removed special logic around subparts in the notice compiler. Now, when looking for a parent, the code first tries to find the _existing_ parent (present if the node is in the tree) and only falls back to speculating what the parent might be.
Resolves 18F/atf-eregs#38
=> Account for deletion of a whole section

regparser/commands/clear.py, tests/commands_clear_tests.py
Builds on #80 ([diff](https://github.com/cmc333333/regulations-parser/compare/preprocess_notices...cmc333333:clear-command)), to add a `clear` command, which deletes any entries in the `.eregs_index` and any related to the `requests` cache
=> Clear command

regparser/commands/preprocess_notice.py, regparser/commands/versions.py, regparser/eregs_index.py, regparser/history/delays.py, regparser/history/versions.py, regparser/notice/xml.py, requirements.txt, tests/commands_versions_tests.py, tests/eregs_index_tests.py, tests/history_delays_tests.py, tests/notice_xml_tests.py
This is the next step to splitting up the `build_from` pipeline. Sketchy outline:
1. ~~preprocess notices~~
2. **generate versions**
3. generate trees from annual XML
4. generate trees from prev trees + changes found in rules
5. generate layers
6. generate diffs
7. post data to the api
This hits the second of those steps by
1. Refactoring the logic around delaying a rule to make it easier to hook into
2. Create a first iteration of a dependency graph for inputs/outputs. This will be responsible for managing which steps of the pipeline are needed. At the moment, it raises an exception for missing dependencies, but it could hypothetically be extended to run subcommands to generate those dependencies in the future
3. Adding a command which reads data from the Federal Register and …
=> Adds `versions` command

eregs.py, regparser/commands/annual_editions.py, regparser/commands/fetch_annual_edition.py, regparser/commands/preprocess_notice.py, regparser/commands/versions.py, regparser/eregs_index.py, regparser/history/annual.py, regparser/history/delays.py, regparser/history/versions.py, regparser/notice/xml.py, requirements.txt, tests/commands_annual_editions_tests.py, tests/commands_versions_tests.py, tests/eregs_index_tests.py, tests/history_delays_tests.py, tests/notice_xml_tests.py
Builds on #83 ([diff](https://github.com/cmc333333/regulations-parser/compare/cmc333333:version-command...cmc333333:annual-commands))
1. ~~preprocess notices~~
2. ~~generate versions~~
3. **generate trees from annual XML**
4. generate trees from prev trees + changes found in rules
5. generate layers
6. generate diffs
7. post data to the api
This adds two new commands -- one for fetching an arbitrary annual edition of the regulation from the CFR and another for parsing all of those annual editions into `Node` trees and serializing the results.
Along the way, this refactors a few libraries, increases logging, and adds help text to the `versions` command.
=> Add commands for processing annual editions

regparser/builder.py, regparser/commands/annual_editions.py, regparser/commands/fill_with_rules.py, regparser/commands/parse_rule_changes.py, regparser/eregs_index.py, regparser/notice/xml.py, tests/builder_tests.py, tests/commands_fill_with_rules_tests.py, tests/commands_parse_rule_changes_tests.py
1. ~~preprocess notices~~
2. ~~generate versions~~
3. ~~generate trees from annual XML~~
4. **generate trees from prev trees + changes found in rules**
5. generate layers
6. generate diffs
7. post data to the api
This adds two new commands -- one for parsing an arbitrary notice (pulling out the relevant changes) and one for using that data to generate new trees. Effectively, this command looks through the generated trees, finds any gaps (where a `Version` exists without a corresponding tree) and attempts to fill those gaps with the data parsed from notices.
A few tweaks to the surrounding code, but nothing major.
=> Commands to parse final rules and build trees with their results

regparser/eregs_index.py
The problem arose with the shelf module if an object containing a shelf wasn't torn down correctly due to an exception being raised. This seemed to be a bug occurring only on OS X.
=> Fix obscure file locking problem

eregs.py, regparser/commands/dependency_resolver.py, regparser/commands/fetch_annual_edition.py, regparser/commands/fetch_sxs.py, regparser/commands/parse_rule_changes.py, regparser/commands/preprocess_notice.py, setup.py
We can determine, by looking at the file name of a missing dependency, how to
resolve that dependency. This adds a `DependencyResolver` base class which is
extended by four commands to describe a resolution to a missing annual
edition, SxS file, rule change file, or notice.
Needed to modify `setup.py` to allow for a recursive call when trying to
resolve.
=> First swing at automated dependency resolution

regparser/api_writer.py, regparser/commands/write_to.py, tests/api_writer_tests.py, tests/commands_write_to_tests.py, tests/http_mixin.py
1. ~~preprocess notices~~
2. ~~generate versions~~
3. ~~generate trees from annual XML~~
4. ~~generate trees from prev trees + changes found in rules~~
5. ~~generate layers~~
6. ~~generate diffs~~
7. **post data to the api**
Once everything is built, send the results to a location on the file system, an API, or a git repository. No dependencies are checked, though that might make sense in a future iteration. Along the way, modifies the api_writer classes so that they can be configured at instance creation time rather than requiring they use the `settings`
=> Write-to / Output command

regparser/builder.py, regparser/commands/fetch_annual_edition.py, regparser/notice/preprocessors.py, tests/notice_preprocessors_tests.py, tests/xml_builder.py
Closes 18f/atf-eregs#54
In one year, the XML might look like:
```
<EXTRACT>
<TAG1>....</TAG1>
<GPOTABLE>...</GPOTABLE>
<TAG2>...</TAG1>
</EXTRACT>
```
and in the next:
```
<EXTRACT>
<TAG1>....</TAG1>
</EXTRACT>
<GPOTABLE>...</GPOTABLE>
<EXTRACT>
<TAG2>...</TAG1>
</EXTRACT>
```
It's safe to say that the table is supposed to be inside the extract; this
preprocessor performs that change. It also applies these preprocessing steps
to annual editions (previously, they had only been applied to notices), and
adds a shortcut for comparing XML trees.
=> Add XML preprocessor to merge EXTRACTs.

regparser/commands/clear.py, regparser/commands/pipeline.py, tests/commands_clear_tests.py
Builds on #88 and #91 -- without them, the `pipeline` command wouldn't be very useful.
The `pipeline` command runs through all of the steps needed to parse a regulation -- it's like `build_from`, but using the split-out commands. The benefit here is that each of these steps is incremental.
Say we've already ran the pipeline and have all of our trees, layers, diffs, etc. I realize that the parser messed up when deriving amendments, so I modify the appropriate notice xml. I then run `preprocess_notice` to get the updated version into the index. Running `pipeline` again will _only_ rebuild the dependencies for that notice (trees, layers, diffs). Similarly, if a new final rule is made, running `pipeline` (after clearing the HTTP cache) will only build trees, layers, etc. associated with that …
=> Pipeline command and tweaks to `clear`

eregs.py, regparser/commands/compare_to.py, requirements.txt, tests/commands_compare_to_tests.py
The goal of this command is to compare your local tree with a remote API. This
is particularly useful for regression tests, to make sure that tweaks to the
parser didn't change the tree/etc. in unexpected ways.
The command calls `write_to` with a temporary directory, then runs through
the files in that directory, comparing each to the same file on the API. If
the file is not present remotely, the user is notified. If the file has a
difference, the user is asked whether or not they want to see the diff.
Interaction looks like:
```
(parser)vagrant@debian8:~/regulations-parser$ eregs compare_to 27 479 https://example.com/api regulation
Writing tree 03-1657
[ .. Snip .. ]
Writing diff 2014-18842 to 2014-18842
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): …
```
=> "Compare to" + requirements updates

regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/tree_utils.py, tests/tree_utils_tests.py, tests/tree_xml_parser_reg_text_tests.py
The trees generated from annual editions and the trees built from final rules contained a few, minor differences. These tweaks to the parser iron the inconsequential ones out.
* Strip whitespace from section and intro paragraph texts. Turns out these vary a tad from edition to edition despite being inconsequential to the regulation
* When removing tags, don't add a space if the tag was preceded or followed by a hyphen or em-dash. Things like
```xml
<p> Abcdef-<prtpage />ghi</p>
```
were being processed as
```
Abcdef- ghi
```
=> Tweaks for 27 CFR 479

regparser/commands/fetch_sxs.py, regparser/commands/parse_rule_changes.py, regparser/federalregister.py, regparser/grammar/unified.py, regparser/history/annual.py, regparser/notice/build.py, regparser/notice/xml.py, tests/commands_fetch_sxs_tests.py, tests/commands_parse_rule_changes_tests.py, tests/grammar_unified_tests.py
Resolves 18f/atf-eregs#62
The `write_to`/`pipeline` commands took a shortcut by re-using the section-by-section analysis JSON. Unfortunately, we were not building all of the fields in that JSON, so writes to the API would be rejected (and any SxS would have been incomplete). This patch hooks into the existing functions to build a full JSON structure to represent the notice.
=> Account for missing notice attrs

regparser/grammar/atomic.py, tests/grammar_atomic_tests.py
Fixes https://github.com/18F/atf-eregs/issues/59
Expands what an atomic section identifier is to include such cases as 479.32a.
=> Citations for alphanumeric sections

regparser/tree/struct.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_paragraph_processor_tests.py, tests/tree_xml_parser_reg_text_tests.py
Addresses #103.
`ParagraphProcessor` instances no longer override the `node_type` of nodes they return with their own `node_type`; instead, the various Matcher objects should set `node_type` in cases where the default of `regtext` needs to be overridden.
This approach overloads `node_type`; previously it only applied at an outer level, expressing that the node was regulation text, or an appendix, etc. It is now also used to express the types of child nodes, in this case that some elements are extracts.
Because the children of the EXTRACT element need to be processed as if they were outside that element, the various Matcher objects’ `derive_nodes` methods need to accept a `processor` argument to give those objects access to the processor's `parse_nodes` method.
=> Handle EXTRACT elements containing more complex child elements.

regparser/commands/preprocess_notice.py, regparser/tree/depth/derive.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/extract_processor.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/commands_preprocess_notice_tests.py, tests/tree_depth_derive_tests.py, tests/tree_xml_parser_reg_text_tests.py
For 18f/atf-eregs#78
Problems this fixes:
* The FR API would return an effective date of `None`; we were assuming that the presence of the key indicated the presence of a date
* We didn't have an exception for `MARKERLESS` paragraphs when asserting that paragraphs at the same depth should have the same marker type
* We were reusing the `RegtextParagraphProcessor` inside `EXTRACT`s, which caused problems as the contents of `EXTRACT`s do not have the structure assumed in Regtext. Resolved by creating a more generic `ExtractParagraphProcessor`
Other improvements/refactors:
* Add more direct debugging info when deriving depth fails. This will actually point out "here's your problem marker"
* Make sure all xml matchers derive from an abstract base class which defines their interface
* Modifies …
=> A few code tweaks for parsing 27 CFR 478

regparser/layer/formatting.py, regparser/notice/preprocessors.py, regparser/tree/xml_parser/tree_utils.py, tests/layer_formatting_tests.py, tests/notice_preprocessors_tests.py, tests/tree_utils_tests.py
Builds on #106 ([diff](https://github.com/cmc333333/regulations-parser/compare/cmc333333:55-footnote-preprocess...cmc333333:55-footnote-data)) for 18f/atf-eregs#55.
Now that the XML includes the exact footnote information we need in line, use that to generate markdown-style inline footnotes (e.g. `text[^1](some footnote)`). Modify the formatting layer to parse these.
Related cleanups/refactors:
* Move fenced, subscripts, dashes, and now footnote -processing into separate classes (rather than a single, ever expanding function)
* Made `get_node_text` more consistent with its space insertion. Previously, subscripts always had a following space. Similarly, pull out the logic to replace an XML tag into a single function to be reused by subscript and footnotes
=> Footnote data 

regparser/tree/struct.py, tests/tree_struct_tests.py
This fixes the issue where after an EXTRACT in the Definitions section the rest of the definitions would be omitted.
=> Tests and fix for Node.depth() not treating EXTRACTs correctly.

regparser/notice/changes.py, regparser/tree/struct.py, tests/notice_build_tests.py, tests/tree_struct_tests.py
Addresses https://github.com/18F/atf-eregs/issues/40
Requires a manual change to the notice XML for 2015-25190 to replace 'the definition of “Customs officer"' to "[label:555-11-p25]".
Bulk of the work done by @cmc333333, I just did some renaming/finishing.
=> Update markerless paragraphs correctly when changed via an amendement

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
Previously, when determining if a paragraph should be split into
subparagraphs, we'd skip over any paragraphs without markers/stars. This meant
that it'd skip over MARKERLESS paragraphs, which is not intended. This patch
modifies this logic to skip over only XML nodes we aren't expecting.
Resolves 18f/atf-eregs#128
This works correctly for 27 CFR 478, 479, 555, 646
=> Modify next_marker logic to account for MARKERLESS

regparser/layer/formatting.py, tests/layer_formatting_tests.py
This is an interim approach, as we should probably turn them into HTML caption elements in the UI. Fixes https://github.com/18F/atf-eregs/issues/105
=> Handle TTITLE elements of GPOTABLEs as full-width header cells.

regparser/history/versions.py, regparser/index/entry.py, tests/history_versions_tests.py
We have been relying on a custom key function which looked at the effective
and publication dates for versions. Now that we've ran in to two notices
published on the same date with the same effective date, we need to also take
into consideration the document id (aka version id). This also moves the
sorting logic into the Version class.
Resolves #129
=> Provide a consistent sort order for Version object

regparser/tree/xml_parser/preprocessors.py, tests/tree_xml_parser_preprocessors_tests.py
Separate the output with spaces. Fixes <https://github.com/18F/atf-eregs/issues/121>.
=> Make preprocessing of <SU> (footnote) elements consistent

regparser/tree/xml_parser/preprocessors.py, tests/tree_xml_parser_preprocessors_tests.py
Addresses https://github.com/18F/regulations-parser/pull/125/files#r46366640
=> Fixes bug where xml preprocessing explodes if there is no tail on the element

regparser/layer/def_finders.py, tests/layer_def_finders_tests.py
Often, definitions will contain multiple, synonymous terms, separated by "or".
This splits those phrases apart into their component definitions. A challenge
here is that "or" isn't a good enough signifier (think of phrases like "red"
or green sign"). To accommodate, this only splits the phrase if all of the
subphrases are single words.
This also converts the keyterm definition search to be a straight parse
attempt. As we only care about the beginning of the line, we don't even need
to try at later parts of the string.
Resolves #65 and assists 18f/atf-eregs#127. Appears to work as intended for 27 CFR 478, 479, 555, 646
=> Split "or" when finding definitions in keyterms.

regparser/layer/key_terms.py, regparser/tree/priority_stack.py, regparser/tree/struct.py, regparser/tree/xml_parser/paragraph_processor.py, tests/tree_xml_parser_paragraph_processor_tests.py, tests/tree_xml_parser_reg_text_tests.py
Thus far, we've been using an ever incrementing number to create unique
identifiers for markerless paragraphs. Unfortunately, when a paragraph is
inserted, every node after it is considered to have changed in this scheme.
This changeset uses a different approach, creating a unique identifier by
hashing the keyterm text.
See 18f/atf-eregs#123 for more context
=> Use keyterm to derive a markerless identifier

regparser/grammar/amdpar.py, regparser/grammar/tokens.py, regparser/layer/key_terms.py, regparser/notice/build.py, regparser/notice/compiler.py, regparser/tree/xml_parser/paragraph_processor.py, tests/grammar_amdpar_tests.py, tests/layer_keyterms_tests.py, tests/notice_build_tests.py, tests/notice_compiler_tests.py, tests/tree_xml_parser_paragraph_processor_tests.py
This will be particularly useful when we have a section of definitions where a new definition is added. Further, this PR adds the ability for labels to be described in terms of their contained keyterms, which should make referencing them much easier and give us some flexibility to swap out the underlying hashing mechanic.
For example, we might have the instruction
> Section 478.11 is amended by adding a definition for the term “Nonimmigrant visa” in alphabetical order to read as follows:
Until now there'd be no way to do that without copy-pasting the entirety of 478.11. With this changeset, however, we can say:
>  [insert-in-order] [label:478-11-keyterm(Nonimmigrant visa)]
See changeset comments for more. Resolves 18f/atf-eregs#148
=> Add a command to insert a paragraph in order

README.md
Updates Travis and Coveralls badges to point to the 18F repo, not CFPB.
=> Update build and test reporting badges

regparser/layer/formatting.py, tests/layer_formatting_tests.py
Subscripts used to require that the letter immediately preceding the subscript
be a letter or number. We now also accept the closing paren character. More
importantly, this drops support for the "variable" data field. Although that
information could be useful, trying to figure out nested parentheses isn't
worth the effort.
This change is backwards compatible; -site, which renders the data _was_
converting the text `variable_{subscript}` into `{{variable}}<sub>{{subscript}}</sub>`.
Now we're only giving it `_{subscript}` and leaving the "variable" empty.
For 18f/atf-eregs#155
=> Allow subscripts to follow more letters

regparser/commands/current_version.py, regparser/commands/pipeline.py, regparser/history/annual.py, tests/commands_current_version_tests.py, tests/history_annual_tests.py
Resolves 18f/atf-eregs#160 by adding a mechanism for building only the most recent annual edition of a regulation. This allowed 50 of FEC's 53 regs to parse without issue.
Also resolves an issue where CFR titles with only one volume weren't finding annual editions correctly. See commit messages for more.
=> Gimme the latest!

regparser/tree/depth/derive.py, regparser/tree/depth/optional_rules.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/reg_text.py, tests/tree_depth_derive_tests.py
Assists (maybe resolves?) 18f/atf-eregs#84. This adds a few new rules to depth parsing which removes some symmetries and cases we should ignore. See changesets for specifics.
This speeds up `nosetests` by a few seconds for me and processes the list in 84 in ~1 minute on my machine. Obviously not ideal, but workable, at least.
=> Depth parsing speedups

regparser/layer/formatting.py, regparser/tree/xml_parser/preprocessors.py, regparser/tree/xml_parser/tree_utils.py, tests/layer_formatting_tests.py, tests/tree_utils_tests.py, tests/tree_xml_parser_preprocessors_tests.py
This adds a superscript conversion/layer very similar to our existing subscripts. While superscripts can be signified by `<E T='51'>`, we must also account for `<SU>`s, which are complicated by their dual use with footnotes. To resolve this, we check if potential footnotes and their referenced text both live in the same `<SECTION>`
Also splits out a few helper functions from `get_node_text` and makes the subscript regex more lenient.
This kicks the can down the road regarding using a real markup language. For 18f/atf-eregs#155, though we still need a few changes in the UI to make use of this data
=> Superscripts

docs/commandline.rst, regparser/commands/compare_to.py, tests/commands_compare_to_tests.py
Previously, `compare_to` required a CFR title and part as it called the
`write_to` function. It made its comparisons by writing all of the JSON output
to a temporary directory and walking that directory for comparisons.
This patch changes that interface so that it compares _any_ arbitrary local
JSON to a remote service. This is useful as it:
1. doesn't need to duplicate all of the JSON files. This isn't a problem for
smaller regs, but could pose issues for larger regs with many versions
2. doesn't restrict us to comparing a single regulation
3. removes the coupling with write_to
4. allows us use glob syntax for defining what to compare
=> Rework compare_to interface

regparser/grammar/amdpar.py, tests/grammar_amdpar_tests.py
Extends the AMDPARser to understand that the intro text of _two_ paragraphs are being modified here:
> introductory text of paragraphs (a)(5)(ii) and (d)(5)(ii)
Resolves 18f/atf-eregs#166
=> AMDPARsing for intro text of multiple paragraphs

eregs.py, regparser/notice/compiler.py, requirements.txt, setup.py
Executing `eregs --debug pipeline 27 478 output` will now drop into a ipdb
debugging session on error. This is optional as the interface is quite
unexpected.
Python's default logging output was a bit difficult to read. This uses a
library to add some nicer colors. It also adds a logging message in the
notice compiler
Requires new libs
Example:
=> Add --debug flag + logging colors to `eregs` command

regparser/grammar/amdpar.py, regparser/grammar/tokens.py, tests/grammar_amdpar_tests.py, tests/grammar_tokens_tests.py, tests/notice_diff_tests.py
This looks like a lot of code, but it's almost exclusively composed of converting position args to keyword args.
The implementation of AMDPARsing for phrases like "the introductory text for
paragraphs (a) and (b)" had a bug stemming from the interface for creating
Paragraph tokens. Until now, these tokens were constructed with a list
parameter, describing the "label" to associate with the token (note that this
label is slightly different than the labels used with trees). The position of
elements within this list gave them special meaning, which leads to the type
of error introduced. This modifies the API to accept keyword arguments as
well, so that authors can express their intent a bit better. It also fixes
some test cases which were using the interface incorrectly (again, no doubt
due …
=> Fix bug w/ intro texts AMDPAR; make API safer

regparser/notice/build.py, regparser/notice/diff.py, tests/notice_build_tests.py, tests/notice_diff_tests.py
@grapesmoker pointed this out months ago, but it's finally bit us. The code
which ties amendments (e.g. "revising paragraph (b)") with the contents of
those amendments (i.e. the XML nodes representing the text) had a bug where
only the _last_ AMDPAR was being used to determine the associated SECTION XML.
This rewrites that chunk of code to group by section XML rather than CFR part,
which resolves the immediate issue. The code in this area's still pretty
messy, but it's a tad cleaner now
Also switches some string XML to use a builder and removes some dead lines. Related to 18f/atf-eregs#103
=> Fix bug when associating amendments w/ changes

regparser/tree/xml_parser/paragraph_processor.py, tests/tree_xml_parser_reg_text_tests.py
27 CFR 447 has some funkiness in its diffs due to `PRTPAGE` tags inside `NOTE`s
=> Ignore blank lines in `NOTE`s

regparser/citations.py, regparser/grammar/unified.py, tests/citations_tests.py
Previously, there was special case logic for checking if CFR citations, such
as "26 CFR 111.10" and "26 CFR 111.11(a) through (d)" were actually internal
citations. This generalizes that logic so we can use it outside of the context
of trying to find internal citations. To do this, this moves two functions out
of a function scope (single_citation, multiple_citations), renames a few
things, and adds the CFR title to an internal representation of labels. This
last piece required we add some additional conversion steps as a Node's label
doesn't track CFR titles, yet we want citations to have that ability.
For 18f/atf-eregs#182
=> Split CFR parsing from internal citations

regparser/citations.py, regparser/commands/citations.py, regparser/grammar/atomic.py, regparser/grammar/unified.py, regparser/grammar/utils.py, regparser/tree/paragraph.py, requirements_test.txt, tests/citations_tests.py
Builds on #142; we can close that if this gets merged first.
At the high level, this adds a little script for printing out CFR citations found in a text file, including filling in any sections/paragraphs implicit in phrases like "paragraph (a)(3)(ii) through (vi)". See the individual changesets for details and let me know if I should break this PR up.
Resolves 18f/atf-eregs#182
=> Rework citations for ATF rulings

regparser/grammar/amdpar.py, regparser/grammar/delays.py, regparser/grammar/external_citations.py, regparser/grammar/interpretation_headers.py, regparser/grammar/terms.py, regparser/grammar/unified.py, regparser/grammar/utils.py, regparser/tree/interpretation.py, regparser/tree/xml_parser/appendices.py, regparser/tree/xml_parser/tree_utils.py, tests/grammar_utils_tests.py
Pyparsing's scanString checks every string index for a parsed string. This is
rather slow, particularly when we're expecting _few_ matches in a given search
string. This adds a wrapper for a Pyparsing grammar which builds an initial
regex to reduce the places we are trying to match the grammar. It should _not_
produce false negatives.
In local testing, it reduces the time to parse all of ATF's regs from scratch
by over 50% (~28m -> ~12m)
Resolves #100
=> Add a QuickSearchable grammar wrapper

regparser/citations.py, regparser/tree/depth/markers.py, regparser/tree/depth/optional_rules.py, regparser/tree/xml_parser/flatsubtree_processor.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/us_code.py, tests/citations_tests.py, tests/tree_depth_derive_tests.py, tests/tree_xml_parser_reg_text_tests.py
These changesets add the logic for regulations to include chunks of US Code (as is the case w/ 27 CFR 478.103). This requires a new paragraph processor (as paragraphs in the US Code follow a different hierarchy than the regtext) as well as a trigger for when to switch into US Code mode. This uses a non-standard tag, `USCODE`, as the trigger, though we can change that in the future if needed.
Work is towards 18f/atf-eregs#223, though there's still the matter of making a permanent data tweak (to add the `USCODE` delimiters) and displaying this correctly in the UI.
=> US Code Processor

regparser/notice/compiler.py, regparser/tree/struct.py, regparser/tree/xml_parser/flatsubtree_processor.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/simple_hierarchy_processor.py, tests/notice_compiler_tests.py, tests/tree_struct_tests.py, tests/tree_xml_parser_reg_text_tests.py, tests/tree_xml_parser_simple_hierarchy_processor_tests.py
This adds smarts for parsing for `NOTE` and `NOTES`, specifically the ability to determine paragraph hierarchy within them. To do this, it adds a new type of paragraph matcher and processer which determines the paragraph marker for any paragraphs beginning with `(a)` or `a.` (or `i` or `1`). We've seen notes use both formats.
It also fixes a problem with notice compilation (which was re-ordering nodes based on heuristics and caused problems with `NOTE`s as a result) and the `depth()` function of `Nodes`, which was looking at the node type rather than "where" the node was located in the tree.
For 18f/atf-eregs#187
=> Note as a node type

eregs.py
We missed a few new rules during the last demo due to having a forever cached set of HTTP responses. This limits the cache to three days. It also sets DEBUG logging when the debug flag is set.
Also see 18F/atf-eregs#280. This issue is tied to 18F/atf-eregs#265
=> Add an expiry to the HTTP cache

regparser/grammar/atomic.py, tests/grammar_unified_tests.py, tests/notice_sxs_tests.py
By default Pyparsing only treats " \t\n" as whitespace chars. Unfortunately,
we've ran across a notice with a "thin-space" unicode character. This patch
configures Pyparsing to account for multiple unicode whitespace chars.
An alternative would be to preprocess all XML and replace thin spaces (and the
like) with normal spaces. We'll see once this rule is released in an annual
edition if that's the correct approach.
For 18f/atf-eregs#265
=> Account for more whitespace

regparser/layer/external_citations.py, tests/layer_external_citations_tests.py
Closes 18F/atf-eregs/275.
This mimics regparser/layer/internal_citations.py#L55.
The underlying issue is that citations parsing (both internal and
external) "capture" trailing whitespace. This issue is masked by the
use of strip() before assertions in tests/citations.py.
A cleaner solution would be to fix the underlying issue.
=> Strip external citations

regparser/grammar/amdpar.py, tests/notice_diff_tests.py
When definition paragraphs do not include a paragraph marker, they are
identified _by their embedded definition_. This tweak to the AMDPARser allows
these paragraphs to be found when referred to as:
* definition of “Appropriate ATF Officer”
* definition for “Person”
* definition for the term “Nonimmigrant visa”
* definition of the term “Article”
Resolves 18F/atf-eregs#281
=> AMDPAR definition paragraphs are identified

regparser/commands/compare_to.py, tests/commands_compare_to_tests.py
Rather than just writing to stdout that a file exists locally but not
remotely, use logging.warn. This will emit a nicely colored message.
=> Compare-to: make "nonexistent" warning more obvious

regparser/layer/terms.py, tests/layer_terms_tests.py
Previously, we would look for definitions in _any_ regtext node of the tree,
regardless of whether that node was in an EXTRACT, NOTE, APPENDIX, etc. This
patch changes that to cut off whole subtrees. In this way, we won't find
definitions in NOTE, EXTRACT, etc.
Resolves 18f/atf-eregs#204
=> Don't look for defs in NOTEs, EXTRACTs, etc.

regparser/tree/depth/derive.py, regparser/tree/depth/pair_rules.py, regparser/tree/depth/rules.py
Move all constraints on pairs of paragraph markers into a single module; give
them all the same interface and explain their nature. Also use a named tuple
to make it clear what's being compared.
We had a `sequence` rule which was repeating many of the checks we performed
on pairs of paragraph markers. This removes that redundancy and hopefully
makes it more clear what's being tested
This is a bit more code in terms of number of lines, but should be easier to
test and reason about.
Part of 18f/atf-eregs#251
=> Refactor components of depth parsing

regparser/tree/depth/optional_rules.py, regparser/tree/depth/pair_rules.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/us_code.py, tests/tree_depth_derive_tests.py
Builds on #170 ([diff](https://github.com/cmc333333/regulations-parser/compare/251-refactor-depths...cmc333333:251-skipped-p)) to allow paragraph markers to be skipped, e.g.
```
(c)
NOTE: (d) and (e) have been reserved
(f)
```
It does this by removing the constraint that markers must be "gapless" sequences. This makes that constraint optional (and configurable, in terms of acceptable gap size). Further, it re-adds that optional constraint to US Code and RegText processors to retain previous workings.
Resolves 18f/atf-eregs#251 -- once we add a paragraph processor specific to the import list, we just need to exclude (or configure) this optional constraint.
=> Allow paragraphs to be skipped

regparser/tree/xml_parser/import_category.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/preprocessors.py, regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_paragraph_processor_tests.py
See changeset for more details, but this adds a preprocessing step the ATF's 447.21 to split out each category within the import list into it's own EXTRACT (for now). This code doesn't belong in this core repo -- we will need to split it out and add proper tests once the plugin interface is defined. In the meantime, this gets a proof of concept up and closes 18f/atf-eregs#305
=> Import List preprocessing

tests/commands_diffs_tests.py, tests/notice_build_tests.py, tests/notice_changes_tests.py, tests/table_of_contents_tests.py
Fix assertions that have an unwise dependency on collection order where no
order is guaranteed.
=> Make tests more robust

regparser/builder.py, regparser/tree/xml_parser/extended_preprocessors.py, regparser/tree/xml_parser/preprocessors.py, regparser/tree/xml_parser/xml_wrapper.py, requirements.txt, settings.py
Using stevedore to manage loading of preprocessors specific to projects. This commit only handles preprocessors, but should provide an outline for how to add hooks for any area of the parser.
=> Hooks for preprocessor extensions

regparser/layer/terms.py, tests/layer_terms_tests.py
1. I also noticed that we patch the inflection package for person -> people. My opinion is that we don't need to do it going the other way.
2. Fixed a minor issue where if the singular and plural were the same (e.g. sheep), we would search for it twice.
=> Support singular search terms

README.md
Updating http://cfpb.github.io/eRegulations/ to http://eregs.github.io/eRegulations/ since the shared site has a more comprehensive explanation of the various agencies and repositories involved in this project.
=> Updating CFPB docs link to shared docs link

regparser/grammar/amdpar.py, regparser/layer/key_terms.py, regparser/tree/depth/derive.py, regparser/tree/paragraph.py, regparser/tree/struct.py, regparser/tree/xml_parser/import_category.py, regparser/tree/xml_parser/paragraph_processor.py, tests/layer_keyterms_tests.py, tests/tree_paragraph_tests.py, tests/tree_struct_tests.py
Renames/refactors a bit, but mostly modifies the way IMPORTCATEGORY tags are handled. See commit messages for details.
Continuing to skip tests around the ATF-specific code.
Resolves 18f/atf-eregs#253
Relies on #174 -- please review that first
=> Better hierarchy in IMPORTCATEGORY

regparser/tree/depth/derive.py, regparser/tree/depth/heuristics.py, regparser/tree/depth/markers.py, regparser/tree/depth/rules.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, tests/tree_depth_derive_tests.py, tests/tree_depth_heuristics_tests.py, tests/tree_xml_parser_reg_text_tests.py
This PR for [fec-regs#1](https://github.com/18F/fec-eregs/issues/1) is review-only at this point - not ready to be merged due to lack of tests. Currently it fixes title 11 part 104, whose problem was inconsistent use of emphasis. The solution is to retry solution-less regulations with relaxed constraints, including removal of all emphasis, removal of the depth_type_inverses optional constraint, and removal of the marker_sandwich constraint.
=> Changes for getting FEC regs parsed

.travis.yml, eregs.py, integration_test.py, regparser/commands/compare_to.py, regparser/commands/integration_test.py, test-travis.sh
This patch revises the travis configuration to run unit tests in one environment, and to run integration tests on each downstream client in a separate environment. In the spirit of writing the simplest implementation possible, this proof of concept uses `compare_to` to diff the current parse against the latest parse on each agency's remote, and fails the build on any differences. I think it would be useful to pause for discussion at this point and see what others who are more familiar with the needs of the project have to say.
cc @cmc333333 @tadhg-ohiggins @vrajmohan @anthonygarvan
=> Integration tests

regparser/layer/terms.py, settings.py, tests/layer_terms_tests.py
See changesets for specifics, but at the high level, this 
1) Reduces logic around this config
2) Uses them when looking for terms _being defined_
3) Allows ignores to begin/end with non-word chars
In service of 18f/atf-eregs#313
=> Updates to IGNORE_DEFINITIONS_IN

regparser/layer/terms.py, tests/layer_terms_tests.py
The terms layer was creating inconsistent results -- the same elements were
present, but they would appear in different order. This patch defines a
specific order (by term) for consistency.
Resolves #200
=> Sort term layer results

regparser/commands/current_version.py, regparser/history/annual.py, tests/commands_current_version_tests.py
`eregs current_version`, which is used by `pipeline --only-latest` had been
using the current date when creating a version associated with the annual
edition XML. This patch changes the logic to use the publication date of the
annual edition. While this isn't accurate (it's very unlikely that the last
final rule became effective on the date that the annual edition was
published), it's _consistent_ and safer than implying we've captured final
rules which have become effective after the annual edition's publication.
Resolves #212
=> Use a better date for eregs current_version

regparser/api_writer.py, regparser/commands/notice_preamble.py, regparser/commands/versions.py, regparser/commands/write_to.py, regparser/index/entry.py, regparser/notice/preamble.py, regparser/notice/xml.py, tests/api_writer_tests.py, tests/commands_notice_preamble_tests.py, tests/commands_versions_tests.py, tests/commands_write_to_tests.py, tests/notice_preamble_tests.py
Adds logic to convert notice preambles into `Node` structures and to write that content to an API/disk. This is a naive first draft which doesn't take into account the header labels (e.g. "IX" in "IX. Some Section")
Extends #211; see [diff](https://github.com/cmc333333/regulations-parser/compare/12-prep...13-parse-notice-preambles)
Should resolve eregs/notice-and-comment#13
=> Parse Notice Preambles

regparser/commands/write_to.py, regparser/notice/fake.py, tests/commands_current_version_tests.py
When we parse real notices, we associate string values for CFR parts affected.
Fake notices weren't being processed this way (using real integers). While
using integers is preferred in the long term, for consistency, convert them to
strings.
Resolves #218
=> Make fake notices consistent w/ real

regparser/notice/preamble.py, regparser/tree/xml_parser/paragraph_processor.py, tests/notice_preamble_tests.py
We already use something similar in the appendix-specific code. Also adds
EXTRACT and GPOTABLE matchers for preambles, and explicitly ignores FTNT and
PRTPAGE tags
Should resolve eregs/notice-and-comment#16
=> Add GraphicsMatcher for embedded images

regparser/api_writer.py, regparser/commands/layers.py, regparser/commands/utils.py, regparser/commands/write_to.py, regparser/index/entry.py, tests/commands_layers_tests.py, tests/commands_write_to_tests.py
Builds on #221 [diff](https://github.com/cmc333333/regulations-parser/compare/17-rework-layers...18-preamble-layers)
The high level ideas here:
* have a separate configuration namespace for preamble layers
* process preamble layers when running `layers` (by making the CFR title/part optional)
* look for those layers when writing (`write_to`). Preamble layers are written with the id "preamble:doc_num"
The individual changesets here are probably too confusing to review -- I went back and forth a few times. It may be easiest just to review the final diff.
Resolves eregs/notice-and-comment#18
=> Parse and write preamble layer data

regparser/layer/preamble/internal_citations.py, regparser/tree/struct.py, settings.py, tests/layer_preamble_internal_citations_tests.py
Super simple implementation which matches text like "III.F.4" if that node is
present in the preamble.
Resolves eregs/notice-and-comment#45
Looks like
=> Add simple internal citations layer for preambles

regparser/layer/graphics.py, tests/http_mixin.py, tests/layer_graphics_tests.py
The FR accidentally changed their format for images a few months ago. While they go back and clean this up, we should accommodate their new system. They promised to add the mappings to their JSON output at some point in the future (so we won't need to guess at URLs).
Also performs some cleanup.
Resolves eregs/notice-and-comment#50
=> Add fallback for graphics layer

regparser/test_utils/xml_builder.py, requirements_test.txt, tests/commands_fetch_sxs_tests.py, tests/commands_parse_rule_changes_tests.py, tests/commands_preprocess_notice_tests.py, tests/layer_formatting_tests.py, tests/notice_build_tests.py, tests/notice_dates_tests.py, tests/notice_diff_tests.py, tests/notice_preamble_tests.py, tests/notice_xml_tests.py, tests/tree_xml_parser_note_processor_tests.py, tests/tree_xml_parser_paragraph_processor_tests.py, tests/tree_xml_parser_preprocessors_tests.py, tests/tree_xml_parser_reg_text_tests.py, tests/tree_xml_parser_simple_hierarchy_processor_tests.py, tests/xml_builder.py
Looks like a lot of changes, but >90% are syntactic.
We used `datatree` for building XML easily for tests. This removes that dependency by adding a drop-in replacement. That replacement is a bit cleaner and more concise for our needs. When used indirectly (through `XMLBuilderMixin`), the replacement is backwards compatible (verified by running existing tests). This PR goes one step further and removes all references to `tests.xml_builder` from the core code base. We'll be able to completely remove that file once we're sure that atf-eregs and fec-eregs don't need it.
Resolves #187
=> Remove datatree

regparser/commands/fill_with_rules.py, regparser/index/dependency.py, requirements.txt, setup.py, tests/commands_fill_with_rules_tests.py, tests/commands_layers_tests.py, tests/commands_preprocess_notice_tests.py, tests/index_dependency_tests.py
[Networkx](https://networkx.github.io/) is a general purpose library for working with graphs; [dagger](http://pythonhosted.org/dagger/) is a more specific tool that focuses on file-modification timing. The latter is basically _exactly_ what we want to determine dependencies, but doesn't have Python3 support, and we'll likely get some use from networkx in other contexts.
This PR removes dagger in favor of networkx, which simplifies some of the accounting, but requires a custom "staleness" function based on a topological sort.
Resolves #184
=> Remove dagger, replace with networkx

regparser/commands/annual_editions.py, tests/commands_annual_editions_tests.py
We had been assuming that, if the publication date for an annual edition was
in the past, that XML file exists. This takes a more cautious approach,
verifying that the file is actually available.
Resolves #232
=> Don't assume annual edition exists

regparser/test_utils/node_accessor.py, tests/node_accessor.py, tests/notice_preamble_tests.py, tests/tree_xml_parser_note_processor_tests.py, tests/tree_xml_parser_reg_text_tests.py, tests/tree_xml_parser_simple_hierarchy_processor_tests.py
This moves the second test utility, `NodeAccessor` into a shared space per #214
=> Move NodeAccessor testing logic

README.md
The Travis "build status" badge was broken since it was referencing the old org name, so I updated that. I also added links to regulations-core and regulations-site for easy reference.
=> Updating repo in Travis link and adding links

regparser/notice/xml.py, tests/notice_xml_tests.py
The json returned by `federalregister.meta_data` uses integers for cfr
titles and parts, but our code and tests expect to receive strings. This
patch updates the logic around titles and parts to handle ints instead.
Note: sorts continue to cast to ints in case we ever happen to receive
strings.
To verify, check that parsing a preamble works with this patch (and errors otherwise). BTW, this reminds me that we might want to get this into our integration tests--same applies to anything else we add to -parser that isn't already covered.
cc @cmc333333 @tadhg-ohiggins
=> Handle integer values in federal register json.

regparser/notice/preamble.py, tests/notice_preamble_tests.py
Previously, we had only considered the "supplemental info" section. This patch
expands that logic a bit, inserting an "intro" node which includes agency,
action, summary, etc. information
Resolves eregs/notice-and-comment#157
This doesn't account for the "meta" data about the notice yet.
=> Parse introductory paragraphs in preamble

regparser/commands/sxs_layers.py
Non-sxs layers are prefixed with document type, but sxs layers are not,
leading to errors on calling `write_to` without a cfr title and part
after building sxs layers. This patch prefixes sxs layers with the cfr
document type.
=> Add cfr prefix to sxs layers.

regparser/tree/xml_parser/tree_utils.py, tests/tree_utils_tests.py
While working on a now-shelved issue, I found that two tree_utils functions
did not work the way I expected. The `get_node_text` function was including
text outside of the parameter is was given (e.g. "this tail" in
`<p>text</p>this tail`). Further, the `get_node_text_tags_preserved` wasn't
actually preserving most tags. This patch replaces it with a simpler form
based on `lxml`'s `strip_tags`.
We should expect integration tests to fail, but the diffs should all make
sense.
=> Cleanup xml-munging functions

.dockerignore, .gitignore, Dockerfile, docs/deeper.rst, docs/installation.rst, eregs.py, regparser/commands/clear.py, regparser/commands/pipeline.py, regparser/commands/write_to.py, regparser/index/__init__.py, regparser/index/http_cache.py, tests/commands_clear_tests.py
Adds `Dockerfile` and instructions for using the built image to the docs. This image will contain all of the necessary libs (including the libxml junk, which has consistently been a pain point) to execute the parser. It moves around the HTTP cache to make this easier to run.
To see this in action, copy the wrapper shell script (described in the included docs) and execute:
```sh
./eregs pipeline 27 646
```
You'll see that a newly created "output" directory will become populated. Running the command again, you'll see that the index is maintained.
=> Add install with Docker option

regparser/commands/write_to.py, regparser/tree/struct.py, tests/tree_struct_tests.py
The existing lft id (assigned using the Modified Preorder Tree
Traversal algorithm) has been employed to allow preorder sorting.
=> Revert assignment of preorder_idx to nodes

regparser/commands/write_to.py
We ran into an issue a bit before the most recent demo where layer data wasn't
available for the preamble on the new live site. The data _was_ available
locally. Unfortunately, the order-of-operations in the `write_to` command lead
the layers to be written before the preamble; the API needs to look up the
associated document (i.e. the preamble) when processing the layers, so no
layers were added.
This swaps the order so that trees (regulations and preambles) are written
before their layers
=> Write preambles before writing layers

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
We had previously only allowed images in appendices and notice preambles.
For eregs/notice-and-comment#239
=> Allow images in regtext

regparser/layer/external_types.py, regparser/layer/layer.py
* When generating the FDSYS URL, always order the parameters
* When generating the layer data, order the matches within a single node
Part of a series to make Python3 results match Python2. Split out into different PRs so that comparisons with existing data are easier to spot.
=> Add consistent ordering for external citations

regparser/layer/formatting.py
Via an OrderedDict
Part of a series to make Python3 results match Python2. Split out into different PRs so that comparisons with existing data are easier to spot.
=> Add consistent ordering to the formatting layer

regparser/diff/tree.py, regparser/notice/changes.py, tests/diff_tree_tests.py
Neither change should trip integration tests (which only test a single version of each reg).
Part of a series to make Python3 results match Python2. Split out into different PRs so that comparisons with existing data are easier to spot.
=> Ignore whitespace changes when diffing

regparser/citations.py, regparser/commands/compare_to.py, regparser/content.py, regparser/grammar/amdpar.py, regparser/notice/changes.py, regparser/notice/compiler.py, regparser/notice/xml.py, regparser/tree/interpretation.py, regparser/tree/xml_parser/interpretations.py, regparser/tree/xml_parser/paragraph_processor.py, tests/commands_compare_to_tests.py
As we're moving to an asynchronous model, we'll want to be able to target
relevant logs. We can only target these logs if they have a _name_
=> Avoid raw logging usage; always name loggers

async_eregs.py, eregs.py, regparser/tasks.py
Instructions for running are in the docs. Decided not to include the rq
requirement just yet -- I think it'll be an "optional" when we do.
Index is still based on the file system.
Used `rq` instead of `celery` for ease of use. Doing things like making exceptions failures, listing which processes failed, storing captured logs, etc. all work with minimal fan fare on `rq`.
For eregs/notice-and-comment#379
=> First draft at an async workflow

docs/dev_tasks.rst, docs/overview.rst, regparser/commands/full_tests.py, requirements_test.txt, setup.cfg, test-travis.sh
py.test seems to be the way the winds are blowing, and it's simple enough to swap out. This PR doesn't modify any existing tests, though we may want to simplify them using raw `assert`s, etc. in the future.
Resolves #269
=> Switch to py.test

regparser/layer/formatting.py, regparser/tree/xml_parser/paragraph_processor.py, tests/layer_formatting_tests.py, tests/tree_xml_parser_reg_text_tests.py
We've got an ugly mix of relying on `source_xml` and `tagged_text` for
different things throughout this code base. Right now, the formatting layer
assumes that table information will be present in `source_xml`, yet the
notice-compiling code is only aware of `tagged_text`.
This updates the table-related code to make use of the `tagged_text` field; the other way (modifying notice-compiling code) would be much more difficult. Part of 18F/eregs-platform#19
=> Add tagged_text to table nodes

.travis.yml, integration_test.py, requirements.txt
Also pins pip version. We expect Travis to fail on the EPA tests (as they don't exist yet), but everything else should stay the same.
=> Add EPA to integration tests

Dockerfile, docs/installation.rst, regparser/web/settings/base.py, regparser/web/settings/prod.py, requirements.txt
Allowing our database to be configured via environment variable not only resolves some Docker woes, it'll also be required in production
=> Use djdatabase

regparser/web/settings/prod.py, requirements_test.txt, setup.cfg
* Update flake8
* Drop pep8 requirement
* Temporarily ignore failing rules
Context: flake8 and associated tools have been updated and cleaned up, so that we don't need to pin to specific old versions anymore. You all might want to fix the linter errors that I temporarily (?) ignored in `setup.cfg`, or decide not to care. If you accept this, you'll probably want to make the same changes across repos for consistency.
=> Update flake8 to latest.

regparser/web/jobs/urls.py, regparser/web/jobs/utils.py, regparser/web/jobs/views.py, tests/test_web_api.py
Old names referred /
To internal naming schemes /
Use names for users.
Changes:
- `/job/` -> `/jobs`/
- `pipeline/` -> `regulations/`
- `proposal-pipeline/` -> `notices/`
- `upload` -> `files/`
=> Change URL paths for web API to make more sense to the user.

regparser/web/jobs/models.py, regparser/web/jobs/serializers.py, regparser/web/jobs/urls.py, regparser/web/jobs/views.py, tests/test_web_api.py
“I don't often hash /
But when I hash files, I use /
SHA256.”
=> Switch hashing from MD5 to SHA256.

requirements.txt, requirements_test.txt, setup.py
Set a new version number and update the requirements. This should make it easier to pin this version in downstream applications (e.g. in ATF's docs).
=> Updates to setup.py

regparser/notice/compiler.py, regparser/tree/xml_parser/interpretations.py
Using [radon](http://radon.readthedocs.io/en/latest/) as a guide, this splits up a few of the more egregiously complex functions. This'll be easiest to review commit by commit.
=> A few small refactors to reduce code complexity

regparser/layer/external_types.py, regparser/notice/preamble.py, regparser/notice/xml.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/xml_wrapper.py, tests/layer_external_citations_tests.py
Rather than copy-paste functions, describe them as a configuration of that shared logic. Also rewrites a test file into py.test style.
=> Replace duplicated logic with declarative style

regparser/tree/xml_parser/reg_text.py, tests/tree_xml_parser_reg_text_tests.py
Also combines the get_subpart_title and get_subjgrp_title functions, which
were identical
Should resolve #321
=> Account for E tags in subpart/subject group titles

tests/test_web_api.py
This resolves #322 by deleting the file storage directory after each
test
=> Use a tmpdir for file upload storage

regparser/layer/def_finders.py, regparser/layer/formatting.py, regparser/layer/key_terms.py, regparser/layer/preamble/key_terms.py, regparser/notice/compiler.py, regparser/tree/struct.py, regparser/tree/xml_parser/appendices.py, regparser/tree/xml_parser/interpretations.py, regparser/tree/xml_parser/paragraph_processor.py, regparser/tree/xml_parser/reg_text.py, regparser/tree/xml_parser/us_code.py
We had been testing Node objects for the presence of the `tagged_text`
attribute rather than defining that attribute consistently. Simplify a bunch
of logic by using the attribute consistently.
This _may_ require another change related to serialization; will see when the
integration tests run.
=> Standardize the tagged_text attribute

regparser/grammar/unified.py, regparser/grammar/utils.py, regparser/layer/terms.py, regparser/web/index/models.py
I used kcachegrind to inspect the results of a run on 27 CFR 478's full history and tried to optimize the biggest pain points. This led to four changes:
* Caching the results of singular/plural lookups
* Refraining from fetching Entry.contents for all entries
* Allow QuickSearchable's to have hard-coded regexes (to be more descriptive)
* Re-use QuickSearchable's parsed regex
=> Add a handful of parsing performance boosts

regparser/tree/xml_parser/tree_utils.py
Also uses `format` rather than string concatenation
This should resolve #347.
=> Use unicode literals when parsing super/subtext

docs/new_rules.rst
Quite minor update to remove a deprecated `eregs clear` parameter from the docs.
=> #361: removing deprecated --http_cache parameter

setup.py
Changes should be backwards compatible, but we have a few new features, so this is just a minor version bump.
- Fix docker build #362
- #361: removing deprecated --http_cache parameter #363
- Three parsing tweaks from #355 #359
- Handful of fixes for 37 CFR 42 #357
- Use FR volume/page instead of publication date when sorting #354
- Fixes for EPA integration tests #353
- Use unicode literals when parsing super/subtext #352
- Add command for full-issuance/reissuances #351
- Step 4 of separating out interpretations #349
- Add a handful of flake8 plugins #346
- Separate interpretations part 3 #344
=> Bump version for quarterly release.

interpparser/gpo_cfr.py, interpparser/preprocessors.py, regparser/tree/gpo_cfr/appendices.py
Based on @cmc333333's [comments](https://github.com/eregs/regulations-parser/pull/365#issuecomment-290421748) on #365, I've added a `get_appendix_title` function to `regparser/tree/gpo_cfr/appendices.py`, removed `get_app_title` from `interpparser/gpo_cfr.py`, and replaced all references.
=> #364: WHED appendix title handling rewritten to complement #359

interpparser/amendments.py, regparser/notice/amendments/appendix.py, tests/interpparser/amendments_tests.py, tests/notice/amendments/appendix_tests.py
PR #370 fixes the issue with the `content_for_appendix()` function in `regparser/notice/amendments/appendix.py`.  The same issue crops up in `content_for_interpretations()` in [`interpparser/amendments.py:19`](https://github.com/eregs/regulations-parser/blob/master/interpparser/amendments.py#L19).  This PR mirrors the fix in #370, including a test.
=> Mirroring PR #370 for Interpretations

regparser/web/management/commands/integration_test.py
The new annual edition for FEC's been released, which causes an integration
test failure (as the integration tests cover 2016). Have the integration tests
explicitly verify 2016 rather than whatever the latest is. We can update tests
to 2017 once they are verified.
=> Fix FEC integration tests to a single year.

regparser/notice/xml.py
Per [@cmc333333's guidance](https://github.com/eregs/regulations-parser/issues/369#issuecomment-297752194), adding a `try/except` block around the `amendments` getter for the `NoticeXML` class.  This enables bypassing of parsing errors in other CFR parts.
=> #369: adding try/except to amendments getter
