eregs/regulations-parser

regparser/citations.py
regparser/grammar/atomic.py
regparser/grammar/unified.py
regparser/layer/external_citations.py
regparser/layer/internal_citations.py
tests/external_citation_parse.py
tests/layer_internal_citations_tests.py

Hold off on merge on this one, I'm still working on getting sentences with multiple citations of the form XX CFR YY to parse.
18F/openFEC#234

Fix internal cites

---

regparser/grammar/unified.py
regparser/layer/external_citations.py
tests/layer_section_by_section_tests.py
tests/notice_compiler_tests.py

Per @khandelwal 's comments on the cfpb PR

More docs + flake8

---

build_from.py

Disable diffs with `--no-generate-diffs`.

---

regparser/grammar/amdpar.py
tests/grammar_amdpar_tests.py

For #31. This construction is very prominent in FEC regulations, but likely appears more widely.
Also some flake8 updates, as my text editor tells me so.

AMDPARs with "paragraph xxx of § YYY"

---

regparser/builder.py
tests/builder_tests.py

This resolves two issues:
* When deriving the initial document number from an annual edition of the regulation, we were grabbing the _first_ notice that was effective before the annual edition, as determined by publication date. This logic isn't quite right -- we want the _last_ notice (determined the same way we order notices) so that the annual edition is associated with the correct document number.
* The version generating code assumed that we'd always be working from the beginning of time. This isn't a good assumption in general, but specifically caused us issues as the earliest annual edition for a regulation contained 3 rules. This wasn't a problem for CFPB because their reissuing rules contained the entirety of the reg (so annual editions weren't needed).

Fix bug in fdsys doc number finder. Allow notices to be skipped

---

regparser/tree/xml_parser/reg_text.py

Need to add full support for SUBJGRP later.

Temporary fix to get SUBJGRP content displaying

---

regparser/notice/build.py
regparser/notice/xml.py
tests/notice_build_tests.py
tests/notice_xml_tests.py

Nothing super novel going on here, just moving around and simplifying sections of `regparser.notice.build`

Pull out chunks of notice.build

---

regparser/commands/fill_with_rules.py
regparser/eregs_index.py
tests/commands_fill_with_rules_tests.py
tests/commands_layers_tests.py
tests/eregs_index_tests.py

This should resolve problems related to needing to close the shelve db

Don't keep a reference to the shelve db open

---

README.md

The hope here is that folks who are new to eregs can get oriented quicker in understanding key components.

First pass at adding concept definitions to the README

---

regparser/notice/preprocessors.py
tests/notice_preprocessors_tests.py

This step will both make sure that there's one footnote reference tag per
reference and mark that tag with meta data containing the footnote itself.
That gives us access to the note content when processing the reference,
allowing us to use markdown footnotes (a later PR).
Part of 18f/atf-eregs#55

Add XML preprocessing step for footnotes

---

regparser/diff/tree.py
regparser/tree/struct.py
tests/diff_tree_tests.py

Previously, we were depending on the kindness of `regulations-site` to figure
out how to order the children of a node when displaying a diff. Instead of
having the -site try to recreate the correct order, this patch embeds that
information into the diff.
Along the way, this simplifies FrozenNode's object re-use, gives it a few new
(memoized) properties, and gives it a `clone` method for quick duplication.
Part of 18f/atf-eregs#123 for more context

Include child order modifications in diffs

---

README.md

Note that we use Python 2.7

---

regparser/layer/formatting.py
tests/layer_formatting_tests.py

Addresses https://github.com/18F/atf-eregs/issues/156.

Parse TTITLE into a caption element, the -parser side

---

regparser/tree/xml_parser/preprocessors.py

These modify the XML to meets ATF's needs. No tests currently as they will be
moved into an ATF-specific plugin once that work is ready.

Add ATF-specific preprocessors

---

settings.py

We'll be retiring 18f/fr-notices

Prefer eregs/fr-notices

---

regparser/citations.py
regparser/layer/def_finders.py
regparser/layer/paragraph_markers.py
regparser/layer/table_of_contents.py
regparser/tree/struct.py
regparser/tree/xml_parser/preprocessors.py
tests/layer_paragraph_markers_tests.py

See changesets; the only functional change is in `marker_of`

Hand full of little improvements

---

.gitignore
regparser/notice/xml.py

Fix invalid attribute

---

settings.py

PRing to core as I want to make sure everyone's using the same data

Include ATF settings in core while plugins are figured out

---

regparser/commands/pipeline.py
regparser/commands/sync_xml.py
regparser/index/xml_sync.py

[Resolves https://github.com/18F/atf-eregs/issues/216]
Not sure about names and default values. Also, the `sync` function wasn't tested before, so I didn't update tests, but I'm happy to add tests for the modified function if this behavior makes sense.
ping @cmc333333

Add git pull timeout.

---

regparser/layer/paragraph_markers.py
regparser/tree/xml_parser/reg_text.py
tests/layer_paragraph_markers_tests.py

Reworks the paragraph marker layer to allow markers like "(b) - (d)"
Resolves #252

Paragraph marker layer now accounts for spans

---

.travis.yml
integration_test.py
regparser/commands/compare_to.py
requirements.txt
test-travis.sh

* On successful builds on master, push parses to S3 as current ground truth
* On pull requests and non-master branches, pull cached parses for comparison
Note: I'm using one of my personal buckets here. If this gets merged, we'll want to provision a new 18F bucket.
cc @cmc333333

Cache ground truth parses to S3.

---

regparser/layer/internal_citations.py

Provide context for missing citations

---

.travis.yml

Use CF-managed S3 bucket for integration cache.

---

.travis.yml
integration_test.py

Fixing bad credentials from #209--second attempt!

Move integration bucket

---

regparser/commands/layers.py
regparser/commands/pipeline.py
regparser/commands/sxs_layers.py
regparser/layer/internal_citations.py
regparser/layer/layer.py
regparser/layer/meta.py
regparser/layer/section_by_section.py
settings.py
tests/commands_layers_tests.py
tests/commands_sxs_layers_tests.py
tests/layer_internal_citations_tests.py
tests/layer_meta_tests.py

In prep for the eventual ability to parse and write non-CFR layer data, here's a set of refactoring commits.
See individual changesets for details; part of eregs/notice-and-comment#18

Layer refactors

---

regparser/api_writer.py
regparser/commands/write_to.py
tests/commands_write_to_tests.py

Also updates tests and adds slightly more concise assertions
Relies on 18F/regulations-core#45

Use new doc_type style when writing layers

---

regparser/commands/write_to.py
regparser/tree/struct.py
tests/tree_struct_tests.py

This helps sort the nodes during display

Add a preorder index to the persisted node

---

regparser/notice/xml.py
tests/notice_xml_tests.py

Fix bug with setting comment_doc_id

---

regparser/commands/import_notice.py

XML is not
Actually Unicode
So use binary

Make import_notice open XML file as binary

---

regparser/layer/external_types.py
settings.py
tests/layer_external_citations_tests.py

For eregs/notice-and-comment#393

Add auto-links for external citations

---

regparser/layer/key_terms.py
regparser/layer/preamble/key_terms.py
regparser/layer/preamble/paragraph_markers.py
regparser/tree/struct.py
regparser/tree/xml_parser/appendices.py
regparser/tree/xml_parser/interpretations.py
regparser/tree/xml_parser/paragraph_processor.py
settings.py
tests/layer_keyterms_tests.py
tests/layer_preamble_key_terms_tests.py
tests/layer_preamble_paragraph_markers_tests.py

Probably easiest to step through the individual changesets. Both layers should work out of the box within -site.
Resolves 18F/eregs-platform#2

Add paragraph marker and keyterm layers to preamble

---

regparser/layer/formatting.py
regparser/layer/graphics.py
regparser/tree/xml_parser/flatsubtree_processor.py
regparser/tree/xml_parser/tree_utils.py
tests/layer_formatting_tests.py
tests/layer_graphics_tests.py
tests/tree_utils_tests.py

See individual changesets for descriptions. For 18F/eregs-platform#36

Handful of changes for parsing the eManifest rule

---

Dockerfile

Add manage.py to docker image

---

regparser/commands/sxs_layers.py
regparser/commands/versions.py

Per @tadhg-ohiggins suggestions in #297

Clean up some complicated for comprehensions

---

doc2xml.py

See the file docstring for usage, installation and known limitations
Resolves 18F/eregs-platform#41

Add dox2xml script

---

regparser/tree/xml_parser/reg_text.py
tests/tree_xml_parser_reg_text_tests.py

Identify these spans by the starting section number. Update the section
title to indicate the sections in the span.

[WIP] Merge spans longer than 3 reserved sections

---

requirements.txt

Includes a major security fix around Google Analytics + CSRF

Update embedded Django

---

regparser/tree/xml_parser/preprocessors.py
regparser/tree/xml_parser/xml_wrapper.py
tests/tree_xml_parser_preprocessors_tests.py

* Allows for empty E tags
* Allows for HTML-encoded entities in the XML

Two changes to account for new FR release

---

regparser/tree/xml_parser/tree_utils.py

When removing duplicated chunks of logic, we tend to replace with declarative
code (i.e. just indicating the parts that are unique to each situation). That
tends to make heavy use of an abstract base class:
```python
class SomeBase(object):
__metaclass__ = abc.metaclass
@abc.abstractproperty
def SOME_CONST(self):
raise NotImplemented()
@abc.abstractmethod
def some_logic(self, input_here):
raise NotImplemented()
def process_input(self, input_here, tail):
return self.some_logic(input_here) + self.SOME_CONST + tail
class Example1(SomeBase):
SOME_CONST = '1'
def some_logic(self, input_here):
return input_here * 2
class Example2(SomeBase):
SOME_CONST = '2'
def some_logic(self, input_here):
return input_here * 4
for cls in (Example1, Example2):
print(cls().process_input("input", "tail"))
``` …

Try a decorator-based alternative to abc

---

docs/extension_points.rst
docs/index.rst

Initial docs listing extension points

---

.travis.yml
Dockerfile
regparser/web/management/commands/integration_test.py
test-travis.sh

Also adds an integration test for said build. Should resolve #360

Fix docker build

---

regparser/notice/amendments/appendix.py
tests/notice/amendments/appendix_tests.py

Thanks @meriouma for the original fix and @gregoryfoster for bringing it
up again!

Fix bug around parsing changes to part titles.
